name: CI

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Download source
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: lib
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
      - name: Install dependencies
        run: shards check || shards install --ignore-crystal-version
      - name: Build
        run: make -j
      - name: Run tests
        run: make -j test
      - name: Check formatting
        run: crystal tool format --check
